/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.Thuoc_DAO;
import entity.Thuoc;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author DatPC
 */
public class pnBanHang extends javax.swing.JPanel implements ActionListener {

	/**
	 * Creates new form pnBanHang
	 */
	public pnBanHang() {

		try {
			dao_Thuoc = new Thuoc_DAO();
			
		} catch (SQLException ex) {
			Logger.getLogger(pnBanHang.class.getName()).log(Level.SEVERE, null, ex);
		}
		initComponents();
		AutoCompleteDecorator.decorate(cbxTimThuoc);
		try {
			// TODO add your handling code here:
			listThuoc = dao_Thuoc.getThuocBanHang();
		} catch (SQLException ex) {
			Logger.getLogger(pnBanHang.class.getName()).log(Level.SEVERE, null, ex);
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		popupmenu = new javax.swing.JPopupMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		btnTimThuoc = new javax.swing.JButton();
		pnTabRoot = new javax.swing.JTabbedPane();
		btnThemHoaDon = new javax.swing.JButton();
		try {
			cbxModel = new DefaultComboBoxModel<String>();
			dataThuocCbxModel = dao_Thuoc.getTenThuoc();
			for (String it : dataThuocCbxModel) {
				cbxModel.addElement(it);
			}
		} catch (Exception e) {
			System.out.print(e.getMessage());
		}
		cbxTimThuoc = new javax.swing.JComboBox<>();
		btnDongHoaDon = new javax.swing.JButton();

		popupmenu.setComponentPopupMenu(popupmenu);
		popupmenu.setPreferredSize(new java.awt.Dimension(100, 200));

		jMenuItem1.setText("ThemHD");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		popupmenu.add(jMenuItem1);

		popupmenu.getAccessibleContext().setAccessibleParent(pnTabRoot);

		setPreferredSize(new java.awt.Dimension(1050, 550));

		btnTimThuoc.setBackground(new java.awt.Color(102, 255, 0));
		btnTimThuoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		btnTimThuoc.setText("Thêm Thuốc");
		btnTimThuoc.setBorder(null);
		btnTimThuoc.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnTimThuocActionPerformed(evt);
			}
		});

		btnThemHoaDon.setBackground(new java.awt.Color(102, 255, 0));
		btnThemHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		btnThemHoaDon.setText("Hóa Đơn Mới");
		btnThemHoaDon.setBorder(null);
		btnThemHoaDon.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThemHoaDonActionPerformed(evt);
			}
		});

		cbxTimThuoc.setModel(cbxModel);

		btnDongHoaDon.setBackground(new java.awt.Color(102, 255, 0));
		btnDongHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
		btnDongHoaDon.setText("Ðóng Hóa Ðơn ");
		btnDongHoaDon.setBorder(null);
		btnDongHoaDon.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDongHoaDonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(111, 111, 111)
				.addComponent(cbxTimThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 277,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(52, 52, 52)
				.addComponent(btnTimThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 92,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18)
				.addComponent(btnThemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 92,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(18, 18, 18)
				.addComponent(btnDongHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 106,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addContainerGap(284, Short.MAX_VALUE)).addComponent(pnTabRoot));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(10, 10, 10)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnTimThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnThemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(cbxTimThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnDongHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(22, 22, 22)
						.addComponent(pnTabRoot, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	private void btnThemHoaDonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThemHoaDonActionPerformed
		// TODO add your handling code here:
		soHoaDon++;
		pnTabRoot.addTab("Hóa đơn " + soHoaDon, new pnTab());
	}// GEN-LAST:event_btnThemHoaDonActionPerformed

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jMenuItem1ActionPerformed

	private void btnTimThuocActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTimThuocActionPerformed
		if (pnTabRoot.getSelectedIndex() == -1) {
			soHoaDon++;
			pnTabRoot.addTab("Hóa đơn " + soHoaDon, new pnTab());
		}
		
		String tenThuoc = cbxTimThuoc.getSelectedItem().toString();
		tt = timTheoTen(tenThuoc);

		try {
			JTextField txtSoLuong = new JTextField();
			txtSoLuong.addKeyListener(new KeyAdapter() {
				public void keyTyped(KeyEvent e) {
					char c = e.getKeyChar();
					if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
						e.consume(); // if it's not a number, ignore the event
					}
				}
			});
			String sl = JOptionPane.showInputDialog(txtSoLuong, "Nhập số lượng");
			int soluong = Integer.parseInt(sl);
			if (soluong <= 0) {
				JOptionPane.showMessageDialog(this, "Số lượng phai > 0");
				return;
			}
			if (soluong > tt.getSoLuong()) {
				JOptionPane.showMessageDialog(this, "Số lượng thuốc trong kho không đủ");
				return;
			}

			pnTab tabSelect = (pnTab) pnTabRoot.getSelectedComponent();

			JLabel lbHinh = tabSelect.getLblHinhAnh();
			ImageIcon img = new ImageIcon(new ImageIcon(tt.getHinhAnh()).getImage().getScaledInstance(lbHinh.getWidth(),
					lbHinh.getHeight(), Image.SCALE_SMOOTH));
			lbHinh.setIcon(img);
			tabSelect.getTfMota().setEditable(false);
			tabSelect.getTfMota().setText(tt.getMoTa());

			// hDHTT new HoaDon(soluong, null, null, null);
			double thanhTien = soluong * tt.getGiaBan();
			DefaultTableModel model = tabSelect.getModel();
			boolean check = false;
			int soLuongDat = 0;
			int index = -1;
			for (int i = 0; i < model.getRowCount(); i++) {
				if(tt.getTenThuoc().equals(model.getValueAt(i, 0))) {
					check = true;
					index = i;
					soLuongDat = Integer.parseInt(model.getValueAt(i, 2).toString());
					break;
				}
			}
			if (check) {
				tabSelect.getModel().setValueAt(soLuongDat+ soluong, index, 2);
				tabSelect.getModel().setValueAt((soLuongDat+ soluong) * tt.getGiaBan(), index, 4);
			}else {
				tabSelect.getModel().addRow(new Object[] { tt.getTenThuoc(), tt.getDonVi(), soluong, tt.getGiaBan(), thanhTien });
			}
			
			tabSelect.changeHoaDon(thanhTien);

		} catch (NumberFormatException e) {
			//JOptionPane.showMessageDialog(this, "Vui lòng nhập số");
			return;
		}

	}// GEN-LAST:event_btnTimThuocActionPerformed

	private void btnDongHoaDonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDongHoaDonActionPerformed
		// TODO add your handling code here:
		pnTabRoot.remove(pnTabRoot.getSelectedComponent());
		soHoaDon--;
	}// GEN-LAST:event_btnDongHoaDonActionPerformed

	public Thuoc getThuocSelect() {
		return tt;
	}

	public ArrayList<Thuoc> getDanhSachThuoc() throws SQLException {
		return listThuoc = dao_Thuoc.getThuocBanHang();

	}

	private Thuoc timTheoTen(String tenThuoc) {
		for (Thuoc thuoc : listThuoc) {
			if (thuoc.getTenThuoc().equals(tenThuoc)) {
				return thuoc;
			}
		}
		return null;
	}

	

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnDongHoaDon;
	private javax.swing.JButton btnThemHoaDon;
	private javax.swing.JButton btnTimThuoc;
	private javax.swing.JComboBox<String> cbxTimThuoc;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JTabbedPane pnTabRoot;
	private javax.swing.JPopupMenu popupmenu;
	// End of variables declaration//GEN-END:variables
	private DefaultComboBoxModel<String> cbxModel;
	private ArrayList<String> dataThuocCbxModel;
	private Thuoc_DAO dao_Thuoc;
	private ArrayList<Thuoc> listThuoc;
	private Thuoc tt; // thuoc duoc chon dem ban
	private int soHoaDon = 0;
	//private ArrayList<ChiTietHD> listCTHoaDon;
	//private ChiTietHD hDHTT;

	@Override
	public void actionPerformed(ActionEvent e) {
		throw new UnsupportedOperationException("Not supported yet."); // Generated from
																		// nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

	}

}
