/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import javax.swing.table.DefaultTableModel;

import connectDB.ConnectDB;
import dao.ChiTietHD_DAO;
import dao.HoaDon_DAO;
import dao.KhachHang_DAO;
import dao.Thuoc_DAO;
import entity.ChiTietHD;
import entity.HoaDon;
import entity.KhachHang;
import entity.NhanVien;
import entity.Thuoc;

import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author DatPC
 */
public class pnTab extends javax.swing.JPanel {

	/**
	 * Creates new form pnTab
	 */
	public pnTab() {
		try {
			kh_Dao = new KhachHang_DAO();
			hd_Dao = new HoaDon_DAO();
			chiTietHD_DAO = new ChiTietHD_DAO();
			dao_Thuoc = new Thuoc_DAO();
			ConnectDB.getInstance().connect();
			Connection con = ConnectDB.getConnection();
		} catch (SQLException ex) {
			Logger.getLogger(pnTab.class.getName()).log(Level.SEVERE, null, ex);
		}
		initComponents();
		table.setEnabled(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		String header[] = { "Tiền thuốc", "Đơn Vị", "Số Lượng", "Đơn giá", "Thành Tiền" };
		model = new DefaultTableModel(header, 0);
		table = new javax.swing.JTable();
		jPanel4 = new javax.swing.JPanel();
		spMota = new javax.swing.JScrollPane();
		tfMota = new javax.swing.JTextArea();
		lblHinhAnh = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel6 = new javax.swing.JPanel();
		lblTongTien = new javax.swing.JLabel();
		txtTongTen = new javax.swing.JTextField();
		txtVat = new javax.swing.JTextField();
		lblVat = new javax.swing.JLabel();
		txtTongCong = new javax.swing.JTextField();
		lblTongCong = new javax.swing.JLabel();
		lblTienKhachDua = new javax.swing.JLabel();
		txtTienKhachTra = new javax.swing.JTextField();
		lblTienThua = new javax.swing.JLabel();
		txtTienThua = new javax.swing.JTextField();
		lblKhachCanTra = new javax.swing.JLabel();
		btnHuy = new javax.swing.JButton();
		btnThanhToan = new javax.swing.JButton();
		clock2 = new gui.Clock();

		jButton2.setText("jButton1");

		jButton3.setText("jButton1");

		setPreferredSize(new java.awt.Dimension(1030, 550));

		table.setModel(model);
		jScrollPane1.setViewportView(table);

		tfMota.setColumns(20);
		tfMota.setRows(5);
		spMota.setViewportView(tfMota);

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addComponent(spMota,
						javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));
		jPanel4Layout.setVerticalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(spMota));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(lblHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 729,
								javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(14, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(lblHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addContainerGap()))));

		jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 0)));

		jPanel3.setBackground(new java.awt.Color(102, 204, 0));
		jPanel3.setForeground(new java.awt.Color(255, 255, 255));

		jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(255, 255, 255));
		jLabel1.setText("HOA DON");

		lblTongTien.setText("Tổng tiền");

		txtTongTen.setDragEnabled(false);
		txtTongTen.setEnabled(false);

		txtVat.setDragEnabled(false);
		txtVat.setEnabled(false);

		lblVat.setText("VAT");

		txtTongCong.setDragEnabled(true);
		txtTongCong.setEnabled(false);

		lblTongCong.setText("Tổng cộng");

		lblTienKhachDua.setText("Tiền khách trả");

		txtTienKhachTra.setDragEnabled(true);
		txtTienKhachTra.addKeyListener(new KeyAdapter() {
			public void keyTyped(KeyEvent e) {
				char c = e.getKeyChar();
				if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
					e.consume();
				}
			}
		});
		txtTienKhachTra.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtTienKhachTraActionPerformed(evt);
			}
		});

		lblTienThua.setText("Tiền thừa");

		txtTienThua.setDragEnabled(true);
		txtTienThua.setEnabled(false);
		txtTienThua.addKeyListener(new KeyAdapter() {
			public void keyTyped(KeyEvent e) {
				char c = e.getKeyChar();
				if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
					e.consume(); // if it's not a number, ignore the event
				}
			}
		});
		txtTienThua.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtTienThuaActionPerformed(evt);
			}
		});

		lblKhachCanTra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
		lblKhachCanTra.setText("Khách cần trả ");

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(jPanel6Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel6Layout
						.createSequentialGroup().addContainerGap()
						.addGroup(jPanel6Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(jPanel6Layout
										.createSequentialGroup().addComponent(lblTienKhachDua)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(txtTienKhachTra))
								.addGroup(jPanel6Layout
										.createSequentialGroup()
										.addGroup(jPanel6Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(lblTongCong).addComponent(lblVat)
												.addComponent(lblTongTien).addComponent(lblTienThua))
										.addGap(29, 29, 29)
										.addGroup(jPanel6Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 172,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														txtTongTen, javax.swing.GroupLayout.PREFERRED_SIZE, 171,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(jPanel6Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(txtVat, javax.swing.GroupLayout.DEFAULT_SIZE, 172,
																Short.MAX_VALUE)
														.addComponent(txtTongCong))))
								.addComponent(lblKhachCanTra, javax.swing.GroupLayout.PREFERRED_SIZE, 159,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel6Layout.createSequentialGroup().addGap(12, 12, 12)
						.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblTongTien).addComponent(
										txtTongTen, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblVat).addComponent(txtVat, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblTongCong).addComponent(txtTongCong,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
						.addComponent(lblKhachCanTra).addGap(29, 29, 29)
						.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblTienKhachDua).addComponent(txtTienKhachTra,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblTienThua).addComponent(txtTienThua,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(82, 82, 82)));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel3Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(102, 102, 102))
				.addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addGap(18, 18, 18).addComponent(jLabel1)
						.addGap(18, 18, 18)
						.addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		btnHuy.setText("Hủy");
		btnHuy.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnHuyActionPerformed(evt);
			}
		});

		btnThanhToan.setText("Thanh Toán");
		btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnThanhToanActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
						.addGap(14, 14, 14)
						.addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 127,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
						.addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 114,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(17, 17, 17))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(clock2,
								javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(39, 39, 39)
						.addComponent(clock2, javax.swing.GroupLayout.PREFERRED_SIZE, 17,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(31, 31, 31)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addContainerGap())
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));
	}// </editor-fold>//GEN-END:initComponents

	private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHuyActionPerformed
		// TODO add your handling code here:
		this.removeAll();
		this.repaint();
		this.revalidate();

	}// GEN-LAST:event_btnHuyActionPerformed

	private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThanhToanActionPerformed
		// TODO add your handling code here:\
		if (txtTienThua.getText().length() == 0) {
			JOptionPane.showMessageDialog(this, "Khách hàng chưa thanh toán tiền");
			return;
		}
		KhachHang kh;
		JOptionPaneGetThongTinKH getInforKH;
		do {
			getInforKH = new JOptionPaneGetThongTinKH();
			JOptionPane.showConfirmDialog(null, getInforKH.getPanel(), "Nhập thông tin khách hàng",
					JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
		} while (!getInforKH.checkNhapDL());
		String tenKH = getInforKH.getTxtTenKH();
		String SDT = getInforKH.getTxtSDT();

		kh = new KhachHang(SDT, tenKH);

		// kiểm tra khách hàng tồn tại chưa
		try {
			if (kh_Dao.kTKH(kh) == 0) {
				kh_Dao.themKhachHang(kh);
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		// luu hoa don tai day
		NhanVien nv = new NhanVien(Login.getUser());
		hoaDon = new HoaDon(hd_Dao.getHoaDonTiepTheo(), LocalDate.now(), nv, kh);
		hd_Dao.themHoaDon(hoaDon);
		// luu chi tiet hoa don
		capNhatHoaDon();
		JOptionPane.showMessageDialog(this, "Thanh toán thành công");
		this.removeAll();
		this.repaint();
		this.revalidate();
	}// GEN-LAST:event_btnThanhToanActionPerformed

	private void txtTienThuaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTienThuaActionPerformed
		// TODO add your handling code here:

	}// GEN-LAST:event_txtTienThuaActionPerformed

	private void txtTienKhachTraActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTienKhachTraActionPerformed
		// TODO add your handling code here:
		thanhToan();
	}

	public void thanhToan() {
		try {
			double tienKhachTra = Double.parseDouble(txtTienKhachTra.getText());
			if (tienKhachTra - tienThuocHoaDon < 0) {
				JOptionPane.showMessageDialog(this, "Tiền khách trả phải lớn hơn tổng tiền");
				return;
			}
			txtTienThua.setText(tienKhachTra - tienThuocHoaDon + "");
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, "Vui lòng nhập số");
			return;
		}
	}

	private void capNhatHoaDon() {
		for (int i = 0; i < model.getRowCount(); i++) {
			int soLuong = Integer.parseInt(model.getValueAt(i, 2).toString());
			double giaBan = Double.parseDouble(model.getValueAt(i, 3).toString());

			Thuoc thuoc = new Thuoc(dao_Thuoc.getMaThuoc(model.getValueAt(i, 0).toString()));
			String donVi = model.getValueAt(i, 1).toString();
			ChiTietHD cthd = new ChiTietHD(new ChiTietHD_DAO().getHoaDonTiepTheo(), soLuong, donVi, giaBan, 0.1,
					getHoaDon(), thuoc);
			dao_Thuoc.capNhatSauBan(thuoc.getMaThuoc(), soLuong);
			chiTietHD_DAO.themChiTietHoaDon(cthd);
		}
	}

	public JLabel getLblHinhAnh() {
		return lblHinhAnh;
	}

	public JTextArea getTfMota() {
		return tfMota;
	}

	public DefaultTableModel getModel() {
		return model;

	}

	public JButton getBtnHuy() {
		return btnHuy;
	}

	public void changeHoaDon(double tien) {
		tienThuocHoaDon += tien;
		txtTongTen.setText(tienThuocHoaDon + "");
		txtVat.setText(0.1 * tienThuocHoaDon + "");
		txtTongCong.setText(tienThuocHoaDon + 0.1 * tienThuocHoaDon + "");
		tienThuocHoaDon = Double.parseDouble(txtTongCong.getText());
	}

	public boolean isCloseTab() {
		return closeTab;
	}

	public HoaDon getHoaDon() {
		return hoaDon;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnHuy;
	private javax.swing.JButton btnThanhToan;
	private gui.Clock clock2;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lblHinhAnh;
	private javax.swing.JLabel lblKhachCanTra;
	private javax.swing.JLabel lblTienKhachDua;
	private javax.swing.JLabel lblTienThua;
	private javax.swing.JLabel lblTongCong;
	private javax.swing.JLabel lblTongTien;
	private javax.swing.JLabel lblVat;
	private javax.swing.JScrollPane spMota;
	private javax.swing.JTable table;
	private javax.swing.JTextArea tfMota;
	private javax.swing.JTextField txtTienKhachTra;
	private javax.swing.JTextField txtTienThua;
	private javax.swing.JTextField txtTongCong;
	private javax.swing.JTextField txtTongTen;
	private javax.swing.JTextField txtVat;
	private DefaultTableModel model;
	// private ConnectDB con;
	private double tienThuocHoaDon;
	private boolean closeTab;
	// private boolean CheckThanhToan = false;
	private KhachHang_DAO kh_Dao;
	private HoaDon hoaDon;
	private HoaDon_DAO hd_Dao;
	private ChiTietHD_DAO chiTietHD_DAO;
	private Thuoc_DAO dao_Thuoc;
}
